name: Test KICS action

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Checkmarx KICS Scan
        uses: checkmarx/kics-action@v1.3
        with:
          path: ./
          platform_type: ansible
          fail_on: medium,high
          output_formats: sarif
          disable_full_descriptions: false
          disable_secrets: false
          enable_comments: true
          verbose: true
          output_path: ./
