name: Test KICS action

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run KICS Scan
        uses: Checkmarx/kics-github-action@v1.4
        with:
          path: './'
          ignore_on_exit: results
