name: Test KICS action

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Mkdir myResults
        # make sure results dir is created
        run: mkdir -p myResults
      - name: Run KICS Scan
        uses: Checkmarx/kics-github-action@v1.4
        with:
          path: './'
          # when provided with a directory on output_path
          # it will generate the specified reports file named 'results.{extension}'
          # in this example it will generate:
          # - results-dir/results.json
          output_path: myResults/
          ignore_on_exit: results

      - name: Show results
        run: |
          cat myResults/results.json
