name: run codefresh pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: 'run pipeline'
        uses: codefresh-io/codefresh-pipeline-runner@v5
        with:
          args: '-v key1=value1 -v key2=value2'
        env:
          PIPELINE_NAME: 'my_project/test2'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        id: run-pipeline
